import 'package:aniki/core/domain/anime.dart';

List<Genre> genres = [
  Genre(malId: 1, name: "Action"),
  Genre(malId: 2, name: "Adventure"),
  Genre(malId: 4, name: "Comedy"),
  Genre(malId: 8, name: "Drama"),
  Genre(malId: 9, name: "Ecchi"),
  Genre(malId: 10, name: "Fantasy"),
  Genre(malId: 14, name: "Horror"),
  Genre(malId: 35, name: "Harem"),
  Genre(malId: 13, name: "Historical"),
  Genre(malId: 62, name: "Isekai"),
  Genre(malId: 43, name: "Josei"),
  Genre(malId: 17, name: "Material Arts"),
  Genre(malId: 18, name: "Mecha"),
  Genre(malId: 38, name: "Military"),
  Genre(malId: 19, name: "Music"),
  Genre(malId: 7, name: "Mystery"),
  Genre(malId: 22, name: "Romance"),
  Genre(malId: 42, name: "Seinen"),
  Genre(malId: 16, name: "School"),
  Genre(malId: 24, name: "Sci-Fi"),
  Genre(malId: 25, name: "Shoujo"),
  Genre(malId: 27, name: "Shounen"),
  Genre(malId: 36, name: "Slice of Life"),
  Genre(malId: 20, name: "Parody"),
  Genre(malId: 18, name: "Supernatural"),
  Genre(malId: 30, name: "Sports"),
  Genre(malId: 40, name: "Psychological"),
  Genre(malId: 19, name: "Tragedy"),
  Genre(malId: 32, name: "Vampire"),
];
